### ISSUE TITLE
2017Q4 top priority work items

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-webdev#1057]
Some items have been carried over from 2017Q3 (#897).

### Major

- [ ] Prep for Dart 2.0
- [ ] Prep for Angular 5 - #1065, ... .

### Documentation

- [ ] [new 4.0 features](https://github.com/dart-lang/angular/blob/master/angular/CHANGELOG.md#400):
  - [x] functional attribute directives - #1111
  - [ ] `@deferred` "compile-time" directive
- [ ] forms
  - [ ] adjust sample and prose to promote use of class bindings #366 
  - [x] Remove NgControlStatus from the Forms guide #1106
  - [x] Update angular forms page #1030 (covered style guide, imports, ...)
- [ ] Upgrade examples and docs to use angular_router 2.0 #361, #1058
- [ ] E2E #895 

Others:
- [ ] how to make a Dart web app offline-capable #593
- [ ] Reuse Matan's Medium.com lazy-loading article #582 
- [ ] i18n #866
- [ ] security page updates: HTTP-level vulnerabilities & HTML sanitization #351
- [ ] how to debug your web app #819
- [ ] ng-content and ngProjectAs aren't documented #617
- [ ] best practices #438
- [ ] communication between components via service #437
- [ ] use of Dart logger as part of ng examples #425
- [ ] how to style angular components #348

### Infrastructure

- [ ] gulp tasks: switch to using pump #1042
- [ ] Continue to decrease technical debt of site-www and site-webdev - #637 
- [ ] Sidenav improvements - #1018
- [ ] TOC improvements - #868
- [ ] check external links #784
- [ ] Consolidate Angular subsite and webdev styles - #980
- [x] Consider reducing our need for `docregion`s (and the shredder), by using file selectors and diffs.
- [ ] Consider migrating to Bootstrap 4?
- [x] fix makeExample stylePatterns #374
- [x] Auto-deploy of PR builds to staging servers - #833

### Doc & examples

- [ ] Update [angular][] API docs
  - [ ] Update [angular2.core/Query](https://webdev.dartlang.org/angular/api/angular2.core/Query); also see https://github.com/dart-lang/angular2/issues/249.
  - [ ] https://github.com/dart-lang/angular2/issues/247
- [ ] Update tutorial and its examples to use ACX - #399 (most likely after 5.x)
- [ ] Feature AngularDart Components in the Angular docs #176

[angular]: https://github.com/dart-lang/angular2
[angular_test]: https://github.com/dart-lang/angular_test
[angular_components]: https://github.com/dart-lang/angular2_components
