### ISSUE TITLE
[Meta] Site changes due to upgrade to Angular 5 and Dart 2

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-webdev#1369]
This is a meta issue used to track the completion status of the 5-dev branch. Items are in no particular order at the moment, and mainly list major work items, not minutia.

- [x] Updates due to use of Dart 2 are tracked using #1366 
- [x] Tutorial
  - [x] Setup: explaining new way to serve apps
  - [x] Parts 5 and 6: use **router v2** - #361, #1058
- [x] Guides
  - [x] Router, due to v2 API rewrite - #1058
- [x] Component testing
  - [x] Explain new way to run tests
  - [x] Temporarily use mock pageloader until pageloader v3 is released - #1350
  - [x] Update to pageloader v3 - #1351
- [x] [angular-examples](https://github.com/angular-examples) repos:
  - [x] README (#1431)
  - [x] gh-pages with updated app
- [x] WebStorm - #1582
  - [x] Update screenshots
  - [x] Adjust warning to mention min version
- [x] Remove unnecessary new/const? - #1650
  Waiting on https://github.com/dart-lang/angular/issues/1313

Also:

- Pages to review before Angular 5 final #1422
