### ISSUE TITLE
Upgrade to Angular 5-alpha+10

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-webdev#1483]
Other than the obvious upgrade in package version, changes to the examples and docs will be necessary for the following:

- [ ] `runApp()` replaces `bootstrap()` et all - #1509, etc
- [ ] Switch to static DI
- [x] Switch to using `const` Provider classes

Updates:

- [x] Examples
  - [x] pubspec package version - #1478
  - [x] architecture - #1485
  - [x] attribute-directives - #1485
  - [x] component-styles - #1485
  - [x] dependency-injection - #1491
  - [x] displaying-data - #1504
  - [x] forms - #1504
  - [x] hierarchical-dependency-injection - #1507
  - [x] lifecycle-hooks - #1504
  - [x] lottery - #1504
  - [x] pipes - #1504
  - [x] quickstart - #1481
  - [x] router - #1499. Then close https://github.com/dart-lang/angular/issues/806.
  - [x] security - #1504
  - [x] server-communication - #1504
  - [x] structural-directives - #1504
  - [x] template-syntax - #1504
  - [x] toh-0 to toh-6 - #1481, #1482 
  - [x] user-input - #1504
- [ ] Prose updates. Revisit discussions around bootstrapping:
  - [x] DI page - #1491 (also see #1490 for followup work).
  - [x] Cheatsheet - #1506
  - [ ] glossary, ... . Also related: #1495 - #1509
  - [ ] Drop link-skip rule used to exclude links to the bootstrap method API - #1509
- [x] Changelog - #1503
