### ISSUE TITLE
2018Q2 work log

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-webdev#1484]
Work log. Reorder items using drag-and-drop:

**Active**:
- [ ] Deploy 5-alpha/beta (master) to main server #1567
- [ ] ...

**Next**:
- [ ] Document "include" in analysis-options https://github.com/dart-lang/site-www/issues/971
- [ ] Split component tests into two tasks
- [ ] Example(lifecycle-hooks): E2E failing under Angular +15 #1647
- [ ] run dartfmt --fix on examples
- [ ] Angular docs: mention use of static variables in templates #1630
- [ ] documentation: template reference variable scope #1594
- [ ] Ensure links to API pkg entries are versioned #1563
- [ ] API docs: link to pub docs #1440
- [ ] **Site-shared submodule**: continue (from #637) setup and config. Also see [wiki page](../wiki/Git-submodule-notes).
  - [x] Fix links in /tools/sdk - https://github.com/chalin/site-shared-dartlang/commit/31d431b8341eee3622a018cc9c7f24c2c75c64ed
  - [x] Move src/_assets/images/installer-screenshot-no.png into shared images
  - Update README.md
  - #1489
  - Make prettify.rb into a gem

**Block/awaiting**:
- [ ] Roll stagehand pkg:angular version to beta https://github.com/dart-lang/stagehand/issues/547
- [ ] Make the gallery the primary API reference doc for angular_components #1533
- [ ] explore deployment of angular_components_example via site-webdev.
- [ ] Add README.md to examples/ng/doc #598
- [ ] firebase and superstatic don't redirect `/angular/` to `/angular` #1418
  - [ ] In the meantime, trim trailing slash from `page.url` (e.g., in site version dropdown)
  - This sometimes causes problems: e.g., in router page, the following erroneous link can be generated https://webdev-dartlang-org-dev.firebaseapp.com/angular/guide/router/router/1#add-router-providers 
- [ ] Document ng-container #1540

**Later?**
- [ ] Updated site design followup #1580
- [ ] Document new DI features #1490
- [ ] **Router guide**: add missing sections - #361
- [ ] Cheatsheet code snippets should be excerpt from our main example sources #1495
  - Create cheatsheet docregion tags
  - Find & use a markdown syntax for the bootstrap table.
- [ ] Report invalid <?code-pane?> excerpt path+region references https://github.com/chalin/code_excerpt_updater/issues/31
- [ ] Improve copy-code button UX #1640

**Submitted**:

- [ ] ...

**Done, deployed and confirmed** (selected):

- [x] Upgrade tutorials/get-data/fetch-data to Dart 2 #1663
- [x] Reinstate link checks - #1665
- [x] Delete 'Using Dart with JSON Web Services' #1634 
- [x] Globally set DART_VM_OPTIONS=--preview-dart-2 #1638
- [x] Examples: Drop `new` and unnecessary `const` #1650
- ~[TRIAL] Drop use of `new` from example apps #1611~
- [x] Examples: run analyzer and dartfmt #1651
- [x] ACX lottery examples: ensure apps build #1653
- [x] Upgrade to Angular et all +15 #1645
- [x] Upgrade to SDK 2-dev.62 #1643 
- [x] Examples: upgrade SDK (2-dev.60) and Angular et all (+14) #1628
- [x] Write code_excerpter in Dart
- [x] Router and toh-5 examples need revision #1595
- [x] Test `examples/html` #1622
- [x] Example(server-communication): non-Dart-2 compatible lib results in runtime error #1575
- [x] web-angular: reintroduce basic component tests based on pageloader 3 https://github.com/dart-lang/stagehand/issues/517
- [x] [Meta] Site changes due to upgrade to Angular 5 and Dart 2 #1369
- [x] Angular-examples README files: change build_runner serve to webdev serve #1610
- [x] Remove survey header #1607
- [x] Upgrade to pageloader v3 #1351
- [x] Compress images on webdev and site-shared
- [x] Examples: upgrade to mockito 3.0.0-beta #1599
- [x] Add get started for CLI (non-Webstorm) #1597
- [x] Examples: adjust apps and tests to new `preserveWhitespace` behavior #1605
- [x] Add a HEADER for our May 2018 Survey #1598
- [x] May 2018 logo update https://github.com/dart-lang/logos/pull/4
- [x] Document use of webdev tool #1537, #1547
- [x] Update design: logos, colors, etc #1569
- [x] Frontpage edits #1577
- [x] Add an index page for /examples #1573
- [x] Deployed multi-example repos don't have boilerplate files in subexample folders #1566
- [x] Dart 2 Migration Guide: example source diffs are wrong #1565
- [x] Upgrade to Dart SDK 2-dev.51 #1557 (also for site-www)
- [x] site-www Tutorial on streams
- [x] Examples: update min SDK to be 2.0.0-dev.48.0 #1534
- [x] Upgrade to Angular 5-alpha+11 #1532
- [x] Remove build.release.yaml and use --release #1523
- [x] Rename "Dart 2 Migration Guide" to include "Dart for the web"? #1464
- [x] Upgrade to SDK 2-dev.50 #1536
- [x] Angular: remove `build.*.yaml` files https://github.com/dart-lang/stagehand/issues/485
- [x] Add a banner to webdev.dartlang.org stating that it's for Angular 4 #1520
- [x] chore(examples): .gitignore file cleanup #1526
- [x] [4.x] chore(examples): .gitignore file cleanup #1527
- [x] Routing Overview: page-relative links don't always work #1496
- [x] Git ignore .dart_tool in all angular-examples repo #1512
- [x] E2E are failing under Dart 2-dev.49 for examples using ngFor trackBy #1516
- [x] Upgrade Dart SDK to 2-dev.49 #1515 
- [x] Merge dart-doc-syncer boilerplate into the example boilerplate folder #1513
- [x] Toh-1: make it clearer that the `hero` field gets updated, not duplicated #1510
- [x] Upgrade to Angular 5-alpha+10 #1483
- [x] Setup 4.x branch, merge 5-dev into master #1474
  - [x] Examples: use pageloader mock from master #1528
- [x] Links to deployed example apps result in 404 #1433
- [x] Sitemap's API URLs are wrong #1311

**Meta/planning**:
- [ ] 2018Q2 top priority work items #1456 
- [ ] [Meta] Site changes due to upgrade to Angular 5 and Dart 2 #1369

**Comment by chalin** [comment]
- [ ] https://github.com/firebase/firebase-tools/issues/746 has been fixed: relaunch builds over www and webdev.

**Comment by chalin** [comment]
See 2018Q3 work log #1680
