### ISSUE TITLE
Deploy 5-alpha/beta (master) to main server

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-webdev#1567]
- [x] Create firebase project to hold ng4 docs. Done: `webdev-angular4-dartlang-org`
- [x] 5-alpha/beta (master)
  - [x] Switch to deploying to main server - #1678
  - [x] Set page banner to: This site covers **web development** with **Dart 2**. [Version information](/version) - #1678
  - [x] Rerun DDS so that https://github.com/angular-examples repo READMEs link back to proper site - done except for lifecycle-hooks, which will be addressed via #1647.
- [x] 4.x
  - [x] Switch to deploying to `webdev-angular4-dartlang-org` - #1673
  - [x] Set page banner to This is the **Dart 1.x and AngularDart 4** archive of [webdev.dartlang.org.](https://webdev.dartlang.org) - #1675
  - ~Rerun DDS so that https://github.com/angular-examples repo READMEs link back to proper site~
- [x] 5-dev via https://webdev-dartlang-org-dev.firebaseapp.com:
  - [x] Add a banner mentioning that this site will be going stale, with a link to the corresponding webdev page - #1677
  - ~Auto-redirect (later maybe)~
- [x] Update site-www: ensure that any links to the dev site now point to the main site - https://github.com/dart-lang/site-www/pull/984
- [x] Stagehand - https://github.com/dart-lang/stagehand/pull/552
- [x] Wiki's version/host table
- Update angular docs (e.g., the migration guide (PR) currently links to the dev site); moved to https://github.com/dart-lang/angular/issues/1450.

**Comment by kevmoo** [comment]
@chalin @kwalrath – we're unblocked (we think) for releasing pkg:angular v5-beta

Any blocking issues here?

**Comment by chalin** [comment]
No blocking issues here. (Note that I added a few todo items to the original comment.)

**Comment by kwalrath** [comment]
Nothing I can think of.

**Comment by chalin** [comment]
@kwalrath - I created the `webdev-angular4-dartlang-org` firebase project to hold ng4 docs.

**Comment by kwalrath** [comment]
I believe we'll switch Monday. Switching on a Friday afternoon is too much of a risk.

**Comment by kevmoo** [comment]
Agreed. I'll be OOO – but online a tiny bit.

**Comment by kwalrath** [comment]
We'll need new notes for both sites. How about these:

* v5:
  This site covers web development with **Dart 2**. [Version information](/version).
* v4:
  This is the **Dart 1.x and AngularDart 4** archive of [webdev.dartlang.org.](https://webdev.dartlang.org)

**Comment by kwalrath** [comment]
Since there are links to the existing v5 site (https://webdev-dartlang-org-dev.firebaseapp.com/), let's keep it around awhile and (automatically or not) redirect people to webdev.dartlang.org.

There's no practical way for us to do 302s for every page, unfortunately. An in-page HTML/JS redirect might work. If so, and there's a noticeable delay, we'd want a note like this:

> This preview site has been deprecated in favor of webdev.dartlang.org, which has up-to-date coverage of Dart 2 and AngularDart 5. You will be redirected shortly to the new URL: [webdev.dartlang.org/path/to/this/page](https://webdev.dartlang.org/path/to/this/page)

If an in-page redirect isn't practical, for some reason, the text could be:

> This preview site has been deprecated in favor of webdev.dartlang.org, which has up-to-date coverage of Dart 2 and AngularDart 5. Please visit the new URL: [webdev.dartlang.org/path/to/this/page](https://webdev.dartlang.org/path/to/this/page)

**Comment by chalin** [comment]
All done!

**Comment by kevmoo** [comment]
Woo hoo!
