### ISSUE TITLE
[ng] Angular API entries - ensure code samples are being inserted in pages

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-webdev#162]
As agreed during the 11/30 weekly meeting, our initial strategy for addressing this will be to complete the code-inclusion feature of dartdocs, https://github.com/dart-lang/dartdoc/issues/1105.

Doc samples (from this repo under `public/docs/_examples`):
- [x] Update dartdoc to insert doc sample fragments - https://github.com/dart-lang/dartdoc/pull/1295
- [x] Adjust build scripts for doc sample fragments - #264

API examples ([angular2_api_examples](https://github.com/dart-lang/angular2_api_examples)):
- [x] upgrade API examples https://github.com/dart-lang/angular2_api_examples/pull/4
- [ ] Build fragments for `angular2_api_examples` - #277
- [ ] Adjust build scripts so that dartdoc can pickup fragments - #277
- [ ] Travis: also fetch `angular2_api_examples` repo - #277

cc @kwalrath

**Comment by chalin** [comment]
It is all working, up-to and including the travis build and auto-deploy; e.g., see [angular2.common/AsyncPipe](https://webdev.dartlang.org/angular/api/angular2.common/AsyncPipe-class).
