### ISSUE TITLE
2018Q3 work log

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-webdev#1680]
Work log. Reorder items using drag-and-drop:

**Active**:
- [ ] Deploy 5-alpha/beta (master) to main server #1567
- [ ] ...

**Next**:
- [ ] Document "include" in analysis-options https://github.com/dart-lang/site-www/issues/971
- [ ] Split component tests into two tasks
- [ ] Example(lifecycle-hooks): E2E failing under Angular +15 #1647
- [ ] run dartfmt --fix on examples
- [ ] Angular docs: mention use of static variables in templates #1630
- [ ] documentation: template reference variable scope #1594
- [ ] Ensure links to API pkg entries are versioned #1563
- [ ] API docs: link to pub docs #1440
- [ ] **Site-shared submodule**: continue (from #637) setup and config. Also see [wiki page](../wiki/Git-submodule-notes).
  - [x] Fix links in /tools/sdk - https://github.com/chalin/site-shared-dartlang/commit/31d431b8341eee3622a018cc9c7f24c2c75c64ed
  - [x] Move src/_assets/images/installer-screenshot-no.png into shared images
  - Update README.md
  - #1489
  - Make prettify.rb into a gem

**Block/awaiting**:
- [ ] Roll stagehand pkg:angular version to beta https://github.com/dart-lang/stagehand/issues/547
- [ ] Make the gallery the primary API reference doc for angular_components #1533
- [ ] explore deployment of angular_components_example via site-webdev.
- [ ] Add README.md to examples/ng/doc #598
- [ ] firebase and superstatic don't redirect `/angular/` to `/angular` #1418
  - [ ] In the meantime, trim trailing slash from `page.url` (e.g., in site version dropdown)
  - This sometimes causes problems: e.g., in router page, the following erroneous link can be generated https://webdev-dartlang-org-dev.firebaseapp.com/angular/guide/router/router/1#add-router-providers 
- [ ] Document ng-container #1540

**Later?**
- [ ] Updated site design followup #1580
- [ ] Document new DI features #1490
- [ ] **Router guide**: add missing sections - #361
- [ ] Cheatsheet code snippets should be excerpt from our main example sources #1495
  - Create cheatsheet docregion tags
  - Find & use a markdown syntax for the bootstrap table.
- [ ] Report invalid <?code-pane?> excerpt path+region references https://github.com/chalin/code_excerpt_updater/issues/31
- [ ] Improve copy-code button UX #1640

**Submitted**:

- [ ] ...

**Done, deployed and confirmed** (selected):

- ...

**Meta/planning**:
- [ ] 2018Q3 top priority work items #1679
