### ISSUE TITLE
v5 404s

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-webdev#1690]
Starting July 3 (when we switched to v5), we've had lots of 404s for the following pages (with the first one ahead by 5x):

- [x] /assets/angulardart.png?4= - #1692
- [ ] /api/angular/angular/Directive/host
- [ ] /api/angular/angular/EventEmitter-class
- [x] /assets/dart-webdev-logo.png?4= - #1692
- [ ] /api/angular/angular/QueryList/elementAt
- [x] /examples/ng/doc/toh-2 - #1693
- [x] /examples/ng/doc/toh-6 - #1693
- [ ] /api/angular_router/angular_router/APP_BASE_HREF-constant
- [ ] /api/angular/angular.security/SafeUrlImpl-class
- [ ] /api/angular/angular/EventEmitter/pipe
- ...
- [x] Once assets `og:image` fix is deployed, [force refresh the image](https://developers.facebook.com/tools/debug).

@chalin: I'll refresh the search index. Could you fix the /assets?

**Comment by chalin** [comment]
`og:image` reset, and it is now valid (there was an error before #1692):
> <img width="709" alt="screen shot 2018-07-06 at 13 45 21" src="https://user-images.githubusercontent.com/4140793/42393029-ec066db2-8122-11e8-8de3-0dc1c00a2819.png">

**Comment by chalin** [comment]
@kwalrath - if we aren't going to address the API URLs then this can be closed, right?

**Comment by kwalrath** [comment]
> @kwalrath - if we aren't going to address the API URLs then this can be closed, right?

Yep.
