### ISSUE TITLE
[ng] address broken links in angular API docs

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-webdev#216]
This is a followup to #204. This is somewhat related to some of the extra functionality that will need to be added to dartdoc (#162).

- [x] only generate API docs for public libraries #266
- [x] API entry page URLs back into docs are wrong #273
- [x] docs: some API reference page links refer to TS entries #318
- [x] ignore broken links due to known issues (e.g., dartdoc) #275

**Comment by chalin** [comment]
As of #275, no warnings or errors are reported:
```
------------------------------------------------------------------
Crawling...

Stats:
  222672 links
    3505 destination URLs
     338 URLs ignored
       0 warnings
       0 errors

------------------------------------------------------------------
```
