### ISSUE TITLE
[ng] break dependence on ng.io

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-webdev#232]
This is a summary issue tracker:
- [x] Jade, #205 
  - [x] Dart Jade sources, #218
  - [x] shared TS Jade sources
     - [x] repatriate TS `_cache`, #231, #234
- [x] Dart sample code, #224
- [x] resources, #233
- [x] locally build:
  - [x] `api-list.json`, #227
  - [x] `cheatsheet.json`, #223 
  - [x] code fragments, #222, #224
- [x] update README.md with simplified setup procedure, #235
- [x] ensure that the `dart-doc-syncer` works with the new setup; see 
   https://github.com/angular/dart-doc-syncer/issues/21

**Comment by chalin** [comment]
Reopening until the `dart-doc-syncer` works with the new setup.

**Comment by chalin** [comment]
dds changes merged!
