### ISSUE TITLE
Add e2e tests for Developer Guide Dart examples

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-webdev#261]
_From @chalin on May 25, 2016 18:23_

- [x] attribute-directives - angular/angular.io#1765
- [x] component-styles - #459
- [x] hierarchical-dependency-injection
- [x] server-communication - angular/angular.io#1423
- [x] lifecycle-hooks - angular/angular.io#1768
- [x] pipes - angular/angular.io#1353
- [x] router - #460
- [x] structural-directives

There are no `testing` and `configuration` chapters yet. Contributes to angular/angular.io#1521.

_Copied from original issue: angular/angular.io#1523_
