### ISSUE TITLE
[ng] 2017Q1 top priority work items

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-webdev#321]
- [x] Update to Angular 3 - #325 
- [ ] examples and testing 
  - [ ] #195 - document (and switch to using) [NgTestBed](https://docs.google.com/document/d/1IuiCQt6m5GJxgDZYJTkfK1b5Va0CazQAQH1-wm18Acs/edit?usp=sharing); also see [pub angular_test package](https://pub.dartlang.org/packages/angular_test)
  - [x] reorganize `_examples` sources - #464
  - [x] meta task tracker - #469
- [ ] Add documentation for **angular_components** (ACX):
  - [x] Get Started sample - #401
  - [ ] Tutorial samples - #399
- [ ] API doc updates, e.g.
  - [x] docs: some API reference page links refer to TS entries - #318 
  - [ ] API docs: add @source examples - #274, #362
- [ ] **Forms** page:
  - [x] Address #114, deprecating use of `NgControlStatus`
  - [ ] recommend use of class bindings over `ngClass` #366
  - (3.0) Update to conform to new package
- [ ] **Router** page:
  - [x] Add (legacy) **router** page - #198
  - [ ] Iterative improvements - #361
  - (3.0) Update to conform to new package
- [ ] **Security** page:
  - [x] Add initial **security** page - #263 
  - [ ] Updates - #351

-----
TS doc items that it might well be worth porting:
- [x] TS-side updates - #368
  - [x] **hierarchical-dependency** chapter - #371, #429
  - [x] **template-syntax**, etc - #442
  - [x] **structural-directives**, etc - #432
  - [x] **forms** page (https://github.com/angular/angular.io/pull/3159) - #337
- [x] Add `<base href>` as part of all samples - #358, #480
- [**Deployment** guide, like the new TS page](https://angular.io/docs/ts/latest/guide/deployment.html).

**Comment by kwalrath** [comment]
We'll also need to document (and switch to using) [NgTestBed](https://docs.google.com/document/d/1IuiCQt6m5GJxgDZYJTkfK1b5Va0CazQAQH1-wm18Acs/edit?usp=sharing).

**Comment by kwalrath** [comment]
#270 added the initial security page. @chalin what updates are still needed to match the TS page?

**Comment by chalin** [comment]
The TS security page has a section on "HTTP-level vulnerabilities" which the Dart version does not (yet).

**Comment by chalin** [comment]
**2017/02/22 Status update**
- [ ] API docs: [pending API doc PRs][ng2pr]; **waiting** for PRs to be approved/merged before making new ones.
- [ ] Forms page: **awaiting** an answer to [Ted's question][tedq].
- Router guide:
  - [ ] **awaiting** an answer to email of Feb 13 to Matan et all, asking about ETA for new router API, to know if it is worth documenting some aspects of the "old" (i.e., current) API
  - [ ] Can work on illustrating component reuse.
- [ ] Security page: **awaiting** answer to XSRF and XSSI question (emailed Feb 17).

Aside from the many pending issues to be progressively addressed, possible next major work items:

- Rewrite tutorial to use ACX? 
- Start writing and documenting tests that make use of NgTestBed. Is it ready?

[ng2pr]: https://github.com/dart-lang/angular2/pulls/chalin
[tedq]: https://github.com/dart-lang/site-webdev/issues/340#issuecomment-278512684

**Comment by chalin** [comment]
Q1 is over. See **2017Q2**, #527.
