### ISSUE TITLE
[Dart] resync Dart .jade files, post-TS-RC5

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-webdev#368]
Originally, https://github.com/angular/angular.io/issues/2077.  Here is the original comment from 2077 (showing remaining guide pages):

Follow up to https://github.com/angular/angular.io/issues/2043.
- [x] guide/architecture.jade
- [x] guide/attribute-directives.jade - #427
- [x] guide/component-styles.jade
- [x] guide/dependency-injection.jade
- [x] guide/displaying-data.jade - #430
- [x] guide/hierarchical-dependency-injection.jade - https://github.com/angular/angular.io/issues/2080
- [x] guide/lifecycle-hooks.jade - https://github.com/angular/angular.io/issues/2141
- [x] guide/pipes.jade
- [x] guide/security.jade
- [x] guide/server-communication.jade - #448
- [x] guide/structural-directives.jade
- [x] guide/template-syntax.jade - https://github.com/angular/angular.io/issues/2121
- [x] quickstart.jade - https://github.com/angular/angular.io/issues/2078, https://github.com/angular/angular.io/issues/2089
- [x] tutorial/toh-pt6.jade - https://github.com/angular/angular.io/issues/2095

**Comment by chalin** [comment]
All subtasks completed.
