### ISSUE TITLE
[meta] consolidate ng/acx samples under site-webdev/examples

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-webdev#469]
- [x] reorganize doc samples under `/examples` #468
- [x] Adjust other tools to new example folder layout
  - angular/dart-doc-syncer#25 --> moved to #507
  - chalin/api_doc_updater#3 - no changes are necessary atm.
- [x] migrate `angular2_api_examples` to `/examples` https://github.com/dart-lang/angular2_api_examples/issues/8
  - [x] adjust webdev build process (which currently fetches `angular2_api_examples`) - #505

**Comment by chalin** [comment]
Done
