### ISSUE TITLE
[ng] 3.0.0-beta release checklist

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-webdev#507]
Update:
- [x] config:
  - [x] `*_RELEASE` environment variables - #562
  - [x] `.travis.yml`: remove `ng3` argument to firebase deploy script so that it falls back to deploying to the main site - #562
  - [x] `_config.yml` - change `acx_api` link to refer to webdev/components/api - #562
  - [x] `scripts/install-dart-sdk.sh` revert to `stable` channel once SDK 1.23 is released - #561 
- [x] Examples:
  - [x] Example `pubspec.yaml` files
    - [x] sdk version to '>= 1.23.0 <2.0.0' - #561
    - [x] acx and ng release version  - #512, #552
    - [x] fix `examples/ng_test/github_issues/pubspec.yaml`, since `pub get` fails - #573
  - [x] https://github.com/angular-examples/ repos.
- [x] Docs and examples
  - [x] Drop EventEmitter from the docs and examples - #566
- [ ] tools and templates
  - [ ] angular/dart-doc-syncer#25 (carried over from #469) - angular/dart-doc-syncer#28
  - [x] stagehand ng templates
    - [x] Consider adding angular_test to ng web simple template (follow-up to #478)
- [x] Tests:
  - [x] re-enable ng_test tests
  - [x] re-enable ng doc tests: (undo #545) - see #552
- [x] [angular_components](https://github.com/dart-lang/angular_components)
  - ~send dartdocs.org a PR to redirect, once we've published - https://github.com/astashov/dartdocs.org/issues/43~
  - [x] submit https://github.com/dart-lang/angular_components/pull/74
- Other:
  - [x] _Move testing text out of toh-0_, #506

**Comment by chalin** [comment]
@kwalrath - All done!
