### ISSUE TITLE
2017Q2 top priority work items

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-webdev#527]
Some items have been carried forward from [2017Q1](321).
- [x] Finalize transition of docs to 3.0 - #507
- [x] Prep for Dart 1.24 - #701
- [ ] decrease technical debt of site-www and site-webdev - #637 
  - [x] convert remaining .jade files to .md #768
- [x] Document how to **test web apps** using [angular_test][] and possibly other means, #195
  - [x] Add tests to examples
- [ ] Switch to HashLocationStrategy as routing strategy for doc samples - #252
- [ ] Prep for angular 4.0 - #670
- [ ] Use [angular_components][] (ACX), #176; Update tutorial and its examples next - #399
- [ ] curate codelabs - #680
- [ ] Update [angular][] API docs
  - [x] #274, #362
  - [ ] Update [angular2.core/Query](https://webdev.dartlang.org/angular/api/angular2.core/Query); also see https://github.com/dart-lang/angular2/issues/249.
  - [ ] https://github.com/dart-lang/angular2/issues/247

[angular]: https://github.com/dart-lang/angular2
[angular_test]: https://github.com/dart-lang/angular_test
[angular_components]: https://github.com/dart-lang/angular2_components

Also generally
- Sync updates made to corresponding ng.io pages #737
- Continue iterative improvements to various pages such as Forms (#366), Router (#361), and Security (#351).

**Comment by chalin** [comment]
See #897.
