### ISSUE TITLE
decrease technical debt of site-www and site-webdev

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-webdev#637]
As @filiph, mentioned, this is in part motivated by the currently poor authoring experience (#208) -- i.e., it takes too long for a site/page refresh after a minor edit:

Proposals:
- [x] Transition away from Jade towards more use of markdown
  - [x] tutorial index, toh-0
  - [x] toh-1 #691 
  - [x] toh-2 #721
  - [x] toh-3 #722
  - [x] many other pages were handled via #713
  - [x] all remaining files #768 
- [x] Curate repo, removing obsolete Jade and Harp support files #896
- [ ] Share site infrastructure (Jekyll plugins, build scripts, etc.)
  - [x] Setup a site-shared submodule
  - [x] Factor out code excerpter. Done! Currently at https://github.com/chalin/code-excerpter. Also: #1402

cc @filiph @kwalrath

**Comment by chalin** [comment]
Closed via #1472
