### ISSUE TITLE
[ng] 4.0 prep

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-webdev#670]
- [x] [4.0.0-alpha+3 changes](https://github.com/dart-lang/angular/blob/master/angular/CHANGELOG.md#400-alpha3)
  - [x] `COMMON_DIRECTIVES` &rarr; `CORE_DIRECTIVES, formDirectives`
  - [x] Add `angular_forms/angular_forms.dart` to files using `formDirectives`
- [x] [4.0.0-alpha+2 changes](https://github.com/dart-lang/angular/blob/master/angular/CHANGELOG.md#400-alpha2):
  - [x] `package:angular/router.dart` &rarr; `package:angular_router/angular_router.dart`
  - [x] `angular/platform/common.dart` and `angular/platform/common_dom.dart` &rarr; `angular/angular.dart`
  - [x] Rename `FORM_DIRECTIVES` to `formDirectives`.
  - [x] Fix ddc compiler errors in examples #703, re-enable skipped tests.
  - [x] Replace injected `ElementRef` by `Element` #948
- [x] [4.0.0-alpha+1 changes](https://github.com/dart-lang/angular/blob/master/angular/CHANGELOG.md#400-alpha1)
- [x] [4.0.0-alpha changes](https://github.com/dart-lang/angular/blob/master/angular/CHANGELOG.md#400-alpha):
  - [x] replace `/deep/` (and `>>>`) by `::ng-deep` #949
  - [x] Remove references to `resolved_identifiers` #824
  - [x] Adjust component-styles example now that [CSS @import is working](https://github.com/dart-lang/angular2/commit/1e276958988606d67100ff1e5356cd10a8976d6a) - #669
  - [x] Enums and globals can now be accessed in templates. Fix docs and examples (e.g. template-syntax). Cf. https://github.com/dart-lang/angular2/issues/374
   - [x] address package rename/repo relocation for angular2 and angular_test #786

Other:
- [x] #880: add API docs to sitemap?
- [x] fix sitemap API entries - followup to https://github.com/dart-lang/site-webdev/pull/888#issuecomment-319745549
- [x] update redirect for angular2.common*
- [x] ensure `github_issues` app is running on latest NG version, https://github.com/dart-league/ng_bootstrap/issues/74, https://github.com/dart-league/ng_bootstrap/issues/78
- [x] from https://github.com/dart-lang/site-webdev/pull/853#issuecomment-316862196: 
  > request an immediate re-indexing when we do change the [API] URLs

Maybe:
- ~Post Dartium: no need for pkg/browser, dart_to_js_script_rewriter, etc #872~

**Comment by kwalrath** [comment]
I think we need to improve our redirects. I did a google search for AfterContentInit, which sent me to https://webdev.dartlang.org/api/angular2/angular2/AfterContentInit-class, which gives me a 404.

**Comment by kwalrath** [comment]
PR #1000 attempts to fix that 404.

**Comment by kwalrath** [comment]
And it seems to have worked. Whew.

**Comment by chalin** [comment]
Thanks for catching that! (I think that my original plan was to use /angular* as a pattern, but your fix works nicely too.)

Finally done (wow, this has been open since the end of May :).
