### ISSUE TITLE
Improve Travis config: Dart dev, superstatic, etc

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-webdev#697]
- [x] Switch to using https://github.com/firebase/superstatic so that Travis builds don't need authentication in order to locally serve the built site. (Among other things, this will allow link check to run in PRs.) -  #698
- [x] Don't launch `content_shell` for the doc build task - #704
- [x] Add Dart `dev` (in addition to the currently hard-coded `stable` channel) to the matrix - #706
- ~Switch to using [headless Chrome](https://developers.google.com/web/updates/2017/04/headless-chrome) (v59)~.
- ~Switch to using Travis [build stages](https://blog.travis-ci.com/2017-05-11-introducing-build-stages)~.

cc @kwalrath @kevmoo

**Comment by chalin** [comment]
All items are done except for:
- Using headless chrome: since `content_shell` 1.24-dev is working now, let's stick with that.
- Travis build stages ... which can wait for a rainy day :).

So closing this issue.

**Comment by chalin** [comment]
Actually, under the 5-dev branch we complete all subtasks:
- [x] Switch to using [headless Chrome](https://developers.google.com/web/updates/2017/04/headless-chrome) - #1267, #1283
- [x] Switch to using Travis [build stages](https://blog.travis-ci.com/2017-05-11-introducing-build-stages) - #1324
