### ISSUE TITLE
Prep for Dart 1.24 and use of dartdevc

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-webdev#701]
Dart 1.24 proper: ensure Travis checks are all green (they were originally failing for 1.24-dev) - #685
- [x] Update `content_shell` command line flags - #695
- [x] Update minimal version of `test` package to 0.12.21.
   (Webdev angular_test-based tests fail under 1.24 when using the previous version.) - #702 

Dart 1.24 and the DDC:
- [WIP] Fix ddc compiler errors in examples and "unskip" the corresponding E2E tests #703
- [WIP] Reorg code of examples in support of better pub/ddc modularization #713
- [x] Examples `pubspec.yaml`:
  - [x] Add new `web:compiler:...` config - #684
  - [x] Update minimal version of SDK in pubspecs to be 1.24 #733

Also see: Update examples to use dartdevc+Chrome workflow #676

Also note that `angular_test`s don't seem to run locally under MacOS: https://github.com/dart-lang/angular_test/issues/63

**Comment by chalin** [comment]
Done for the "prep" part. See individual issues for longer remaining conversions that are still in progress:
- [WIP] Fix ddc compiler errors in examples and "unskip" the corresponding E2E tests #703
- [WIP] Reorg code of examples in support of better pub/ddc modularization #713
