### ISSUE TITLE
[ng] Fix ddc compiler errors in examples

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-webdev#703]
Some [E2E tests **fail** when examples are built using the ddc](https://travis-ci.org/chalin/site-webdev/jobs/239936736), apparently because of errors reported during compilation.

```nocode
Suites passed:
  examples/ng/doc/architecture
  examples/ng/doc/attribute-directives
  examples/ng/doc/component-styles
  examples/ng/doc/dependency-injection
  examples/ng/doc/displaying-data
  examples/ng/doc/forms
  examples/ng/doc/hierarchical-dependency-injection
  examples/ng/doc/pipes
  examples/ng/doc/quickstart
  examples/ng/doc/router
  examples/ng/doc/security
  examples/ng/doc/structural-directives
  examples/ng/doc/toh-1
  examples/ng/doc/toh-2
  examples/ng/doc/toh-3
  examples/ng/doc/toh-4
  examples/ng/doc/user-input
Suites failed:
  examples/ng/doc/lifecycle-hooks
  examples/ng/doc/server-communication
  examples/ng/doc/template-syntax
  examples/ng/doc/toh-5
  examples/ng/doc/toh-6
```

Analysis:
- [x] lifecycle-hooks, toh-5: **errors are false positives**, see https://github.com/dart-lang/sdk/issues/29803 which have already been fixed (these errors will be downgraded back to warnings): <br>
  `[error] Element 'Location' from SDK library 'dart:html' is implicitly hidden by 'location.dart'.`<br><br>
  - [x] unskip lifecycle-hooks test once a fix lands in the SDK
  - [x] unskip toh-5 test once this is fixed
  - [x] unskip toh-6 test once this is fixed
- [x] server-communication, toh-6:
  - [x] [ng] examples(toh-6, server-communication): switch to using the stream_transform pkg #709 
  - [x] unskip server-communication test once this is fixed
  - [x] unskip toh-6 test once this is fixed
  - [x] ~[dartdevc reports type errors over `package:stream_transformers` #29805](https://github.com/dart-lang/sdk/issues/29805)~
- [x] template-syntax:
  - [x] unskip corresponding tests once this is fixed
  - [x] [In TrackByFn typedef, index parameter should be an int not a num #431](https://github.com/dart-lang/angular2/issues/431)
  - [x] ~[dartdevc reports: (int, Hero) → int can't be assigned to (num, dynamic) → dynamic #29806](https://github.com/dart-lang/sdk/issues/29806)~

Relates to #701.

**Comment by chalin** [comment]
The template-syntax errors are shown below. The first has been reported via https://github.com/dart-lang/angular2/issues/431. The second still needs to be investigated.
```nocode
[error] A value of type '(int, dynamic) → int' can't be assigned to a variable of type 'TrackByFn(num, dynamic) → dynamic'. (package:template_syntax/app_component.template.dart, line 4058, col 36)
[error] A value of type 'String' can't be assigned to a variable of type 'Hero'. (package:template_syntax/app_component.template.dart, line 4888, col 56)
```

**Comment by chalin** [comment]
The failing E2E tests are currently being skipped (as of #712). I've added a work item to remember to "unskip" the corresponding tests once they are fixed.
