### ISSUE TITLE
[ng] Reorg code of examples in support of better pub/ddc modularization

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-webdev#713]
Contributes to #701.

Examples under `examples/ng/doc`
 - [x] architecture #726
 - [x] attribute-directives #714
 - [x] component-styles #714
 - [x] dependency-injection #727
 - [x] displaying-data + .jade --> .md #728
 - [x] forms + .jade --> .md #730
 - [x] hierarchical-dependency-injection + .jade --> .md #731
 - [x] lifecycle-hooks + .jade --> .md #732
 - [x] pipes + .jade --> .md #734
 - quickstart: no src reorg needed
 - [x] router + .jade --> .md #736
 - [x] security #727
 - [x] server-communication + .jade --> .md #753
 - [x] structural-directives + .jade --> .md #747
 - [x] template-syntax + .jade --> .md #748
 - toh-0: derived from quickstart
 - toh-1: no src reorg needed
 - toh-2: no src reorg needed
 - [x] toh-3 #744
 - [x] toh-4 + .jade --> .md #745
 - [x] toh-5 + .jade --> .md #750
 - [x] toh-6 + .jade --> .md #751
 - [x] user-input + .jade --> .md #746

Codelabs:
- [x] pirate badge (ng2) codelab #755
- [x] acx codelab #759

**Comment by chalin** [comment]
All done! 😅  🎉
