### ISSUE TITLE
2017Q3 top priority work items

### ISSUE THREAD

**Issue by chalin** [dart-lang/site-webdev#897]
Some items have been carried over from 2017Q2 (#527).

### Major

- ~Prep for Dart 2.0~ --> #1057
- [x] Prep for angular 4.0 - #670

### Documentation

- [x] Switch to HashLocationStrategy in examples #252
- **Router** (includes, toh-5 and -6):
  - ~complete & update to use new API #361~ --> #1057 
  - ~Upgrade examples and docs to use angular_router 2.0 #1058~ --> #1057
- ~E2E #895~ --> #1057
- ~Others: forms #366, security #351.~ --> #1057

### Infrastructure

- Decrease technical debt of site-www and site-webdev - #637. Partially addressed in Q3.
- [x] Curate repo, removing obsolete Jade and Harp support files #896

### Doc & examples

- ~Use [angular_components][] (ACX), #176; Update tutorial and its examples next - #399~ --> #1057
- ~Update [angular][] API docs~ --> #1057
  - Update [angular2.core/Query](https://webdev.dartlang.org/angular/api/angular2.core/Query); also see https://github.com/dart-lang/angular2/issues/249.
  - ~https://github.com/dart-lang/angular2/issues/247~ --> #1057
- [x] curate codelabs - #680

[angular]: https://github.com/dart-lang/angular2
[angular_test]: https://github.com/dart-lang/angular_test
[angular_components]: https://github.com/dart-lang/angular2_components

**Comment by chalin** [comment]
#1057 covers Q4

**Comment by chalin** [comment]
Finalized
- Switch to HashLocationStrategy in examples #252

Moving on to Q4 items (#1057).
